sample_response_url = "https://www.digialm.com//per/g01/pub/585/touchstone/AssessmentQPHTMLMode1//GATE2060/GATE2060S1D3808/16135414429172474/CS21S62047139_GATE2060S1D3808E1.html"


# google - sample
#answer_key_url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRcxWRENCxZJe6aPTC2ospREhxroCzayF1KSTdSNyVVHmybITJ3CCzgcdZLPu2SOlSy8aw8KcpssgOi/pubhtml?gid=0&single=true"

# my ans-key generated by cralwer
sample_answer_key_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQqShAMSQMwc7z_4HQwI6d7Gg1M7BlBchf5RoB85n-TRfkw5k2W96ICzsAcO3FFchqghIFZA_KpObAl/pubhtml'
