default:
	# parser
	python3 parse.py -r https://www.digialm.com//per/g01/pub/585/touchstone/AssessmentQPHTMLMode1//GATE2060/GATE2060S1D3808/16135414429172474/CS21S62047139_GATE2060S1D3808E1.html -k https://docs.google.com/spreadsheets/d/e/2PACX-1vQqShAMSQMwc7z_4HQwI6d7Gg1M7BlBchf5RoB85n-TRfkw5k2W96ICzsAcO3FFchqghIFZA_KpObAl/pubhtml -o res.json
t:
	# crawler
	python3 crawler.py